### ISSUE TITLE
 curso-dio-intro-java-i-o

### ISSUE THREAD

**Issue by NildsonKleyton** [cami-la/curso-dio-intro-java-i-o#1]
Olá 

Agora estou aqui :)

Como posso ter acesso ao slide, para poder acessar os link que você menciona durante o curso.

**Comment by cami-la** [comment]
Aqui, amigo: https://docs.google.com/presentation/d/1TN8ZRSYYxoA2DmcHysyIaar_bs5KFTBO/edit?usp=sharing&ouid=101929589707990413603&rtpof=true&sd=true

**Comment by marcioiherrero** [comment]
Boa noite  @cami-la, como vai?
Poderia disponibilizar o restante dos slides do curso "Entrada e Saída de Arquivos (I/O) em Java" da DIO?
Obrigado!

**Comment by marcioiherrero** [comment]
Algum retorno Camila?

**Comment by cami-la** [comment]
> Algum retorno Camila?

Oi, @marcioiherrero bom dia.

Peço descupas, mas procurei aqui nos meus arquivos e não encontrei esses slides. O curso é um pouco antigo e acabei perdendo. :(

**Comment by marcioiherrero** [comment]
Tá ok Camila, agradeço o retorno.
A DIO infelizmente peca nesse sentido, vende os cursos da plataforma e não atualiza as aulas.

**Comment by cami-la** [comment]
Recomendo que você abra uma sugestão de renovação de aulas na plataforma da DIO! 
Estou super à disposição para regravar. Inclusise essa I/O API deu uma boa atualizada nas novas versões do Java.

De qualquer forma, sigo à disposição caso tenha dúvidas.

Bons estudos!

**Comment by LinikerThiers** [comment]
Olá Camila, estou fazendo o curso "Entrada e Saída de Arquivos (I/O) em Java", no exemplo 1 de I/O Data, na execução do exemplo está retornando a Exception `InputMismatchException`, já tentei usar o try catch porém continua dando erro :(
```
Nome da peça: Regata
Tamanho da peça (P/M/G/U): m
Quantidade: 3
Preço unitário: 99.99
Exception in thread "main" java.util.InputMismatchException
	at java.base/java.util.Scanner.throwFor(Scanner.java:947)
	at java.base/java.util.Scanner.next(Scanner.java:1602)
	at java.base/java.util.Scanner.nextDouble(Scanner.java:2573)
	at br.com.dio.java.io.IOBytes.IOData.ExemploIOData.incluirProduto(ExemploIOData.java:33)
	at br.com.dio.java.io.IOBytes.IOData.ExemploIOData.main(ExemploIOData.java:48)

Process finished with exit code 1 
```
e aqui está o método incluirProduto:

```
public static void incluirProduto() throws IOException {
       File f = new File("C:\\Users\\linik\\OneDrive\\Documentos\\roupas.bin");
       PrintStream ps = new PrintStream(System.out);
       ps.flush();
        DataOutputStream dos = new DataOutputStream(new FileOutputStream(f.getPath()));
        Scanner scan = new Scanner(System.in);

        ps.print("Nome da peça: ");
        String nome = scan.nextLine();
        dos.writeUTF(nome);

        ps.print("Tamanho da peça (P/M/G/U): ");
        char tamanho = (char) System.in.read();
        dos.writeChar(tamanho);

        ps.print("Quantidade: ");
        int quantidade = scan.nextInt();
        dos.writeInt(quantidade);

        ps.print("Preço unitário: ");
        double preco = scan.nextDouble();
        dos.writeDouble(preco);

        dos.close();
        scan.close();
        ps.close();

    }
```
poderia ajudar?

**Comment by LinikerThiers** [comment]
Consegui resolver o problema pegando o valor do preço como string, trocar vírgula (caso o dado de entrada for ex: 99,99) por um ponto (ex: 99.99) e transformar essa string em double.
```
ps.print("Preço unitário: ");
        String precoStr = scan.next();
        precoStr = precoStr.replace(",", ".");
        double preco = Double.parseDouble(precoStr);
        dos.writeDouble(preco);
```
e obtive a saída assim passando preço como `99.99`: 
```
Nome da peça: Regata
Tamanho da peça (P/M/G/U): M
Quantidade: 5
Preço unitário: 99.99
O arquivo roupas.bin foi criado com 22 bytes no difetório 'C:\Users\linik\roupas.bin'.

Nome---------------: Regata

Tamanho---------------: M

Quantidade---------------: 5

Preço---------------: 99,99
Total do valor das Peças: 499,95
Process finished with exit code 0
```
passando o preço como `59,99`:
```
Nome da peça: Regata
Tamanho da peça (P/M/G/U): M
Quantidade: 3
Preço unitário: 59,99
O arquivo roupas.bin foi criado com 22 bytes no difetório 'C:\Users\linik\roupas.bin'.

Nome---------------: Regata

Tamanho---------------: M

Quantidade---------------: 3

Preço---------------: 59,99
Total do valor das Peças: 179,97
Process finished with exit code 0
```
Para melhora falta colocar tratamento de exception com `try` `catch` caso o valor da entrada seja diferente do esperado.
Não sei se essa seria a melhor forma de resolver o problema que tive acima, caso exista uma forma melhor ficarei grato em poder aprender!
